Enable the vfs on the nor flash, and other related modify
RockySong/micropython-rocky pull request #23
Opened 2020-05-07 17:14 UTC by CristXu

2020-05-08 00:39 UTC, RockySong commented on ports/nxp_rt1050_60/main.c
> +		_heap_end = _heap_start + 512 * 1024;
为什么需要扩大heap呢？

2020-05-08 00:42 UTC, RockySong commented on ports/nxp_rt1050_60/overlay_manager.c
> +		#endif
去掉#if 1吧

2020-05-08 00:53 UTC, RockySong commented on ports/nxp_rt1050_60/modpyb.c
> +};
建议自己新加的模块不放在modpyb.c里，可以新建一个.c文件

2020-05-08 00:57 UTC, RockySong commented on ports/nxp_rt1050_60/boards/imxrtevk105x/mpconfigboard.h
> +#define MICROPY_HW_HAS_FLASH        (1)
加条件编译，只有当前板子是1060EVK时（不是BOARD_OMVRT1，也不是EVK1050_60_HYPER）才定义MICROPY_HW_HAS_FLASH 为1

2020-05-08 00:58 UTC, RockySong commented on ports/nxp_rt1050_60/main.c
> +        #if MICROPY_HW_HAS_FLASH || defined(EVK1050_60_HYPER)
目前还不支持hyper flash吧？改为"&& !defined(EVK1050_60_HYPER)"

2020-05-08 01:01 UTC, RockySong commented on ports/nxp_rt1050_60/main.c
> +#include "overlay_manager.h"
main.c确实需要这个头文件吗？

2020-05-08 01:05 UTC, RockySong commented on ports/nxp_rt1050_60/main.c
> +	#if MICROPY_HW_HAS_FLASH || (!defined(XIP_EXTERNAL_FLASH) && defined(EVK1050_60_HYPER))
使用逻辑或"||"不合理。
一方面，只要定义了MICROPY_HW_HAS_FLASH，就无视后面条件了
另方面，就算不定义MICROPY_HW_HAS_FLASH，也会在使能了HYPER Flash时启用Flash FS。
建议改成只MICROPY_HW_HAS_FLASH && !defined(EVK1050_60_HYPER) && !defined(BOARD_OMVRT1). 如果将来分别支持OpenMV-RT小板和hyper flash了，再去掉这些条件。

2020-05-08 01:07 UTC, RockySong requested changes
针对改动的代码部分，我把comments inline了。此外，
删除以下不需要的文件：
nxp_rt1050_60/build-imxrtevk105x/genhdr/qstr.i.last
nxp_rt1050_60/build-imxrtevk105x/genhdr/qstrdefs.collected.h
nxp_rt1050_60/build-imxrtevk105x/genhdr/qstrdefs.collected.h.hash
nxp_rt1050_60/build-imxrtevk105x/genhdr/qstrdefs.preprocessed.h 
prj_keil_rt1060/out_evk1050_pybonly_qspi/objects/ExtDll.iex
prj_keil_rt1060/out_evk1050_pybonly_qspi/objects/mpyrt_evk1060_pybonly_qspi.build_log.htm
ports/prj_keil_rt1060/out_evk1050_pybonly_sdram/objects/ExtDll.iex
prj_keil_rt1060/out_evk1050_pybonly_sdram/objects/mpyrt_evk1060_pybonly_sdram.build_log.htm
prj_keil_rt1060/out_evk1050_qspi/objects/ExtDll.iex 
prj_keil_rt1060/out_evk1050_qspi/objects/mpyrt_evk1060_qspi.build_log.htm

2020-05-08 16:08 UTC, CristXu commented
Some new updates for openmvRT -> vfs on flash

2020-05-09 01:11 UTC, RockySong approved these changes
Merge pull request "Enable the vfs on the nor flash, and other related modify" from Crist Xu

2020-05-09 01:11 UTC, merged